//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string KeyFileName {
            get {
                return ResourceManager.GetString("KeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Logs/.
        /// </summary>
        internal static string LogDirectory {
            get {
                return ResourceManager.GetString("LogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string ParamatersFileName {
            get {
                return ResourceManager.GetString("ParamatersFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainsMinute.
        /// </summary>
        internal static string ProcName_ContainsMinute {
            get {
                return ResourceManager.GetString("ProcName_ContainsMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDayTradesTable.
        /// </summary>
        internal static string ProcName_CreateDayTradesTable {
            get {
                return ResourceManager.GetString("ProcName_CreateDayTradesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDayVolumesTable.
        /// </summary>
        internal static string ProcName_CreateDayVolumesTable {
            get {
                return ResourceManager.GetString("ProcName_CreateDayVolumesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertDayTradesData.
        /// </summary>
        internal static string ProcName_InsertDayTradesData {
            get {
                return ResourceManager.GetString("ProcName_InsertDayTradesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertDayVolumesData.
        /// </summary>
        internal static string ProcName_InsertDayVolumesData {
            get {
                return ResourceManager.GetString("ProcName_InsertDayVolumesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastMinute.
        /// </summary>
        internal static string ProcName_LastMinute {
            get {
                return ResourceManager.GetString("ProcName_LastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferDayTables.
        /// </summary>
        internal static string ProcName_TransferDayTables {
            get {
                return ResourceManager.GetString("ProcName_TransferDayTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDayVolume.
        /// </summary>
        internal static string ProcName_UpdateDayVolume {
            get {
                return ResourceManager.GetString("ProcName_UpdateDayVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to securities.
        /// </summary>
        internal static string SecuritiesFileName {
            get {
                return ResourceManager.GetString("SecuritiesFileName", resourceCulture);
            }
        }
    }
}
